[package]
name = "psml"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.31.0", features = ["serialize"]}
indexmap = { version = "1.9.1", optional = true}
serde = { version = "1.0.143", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1.10.3"
